//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureReplicaSpec) DeepCopyInto(out *AzureReplicaSpec) {
	*out = *in
	if in.AccountKey != nil {
		in, out := &in.AccountKey, &out.AccountKey
		*out = new(SecretReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureReplicaSpec.
func (in *AzureReplicaSpec) DeepCopy() *AzureReplicaSpec {
	if in == nil {
		return nil
	}
	out := new(AzureReplicaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseBinding) DeepCopyInto(out *DatabaseBinding) {
	*out = *in
	if in.Restore != nil {
		in, out := &in.Restore, &out.Restore
		*out = new(RestoreSpec)
		**out = **in
	}
	if in.Replicate != nil {
		in, out := &in.Replicate, &out.Replicate
		*out = new(ReplicateSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseBinding.
func (in *DatabaseBinding) DeepCopy() *DatabaseBinding {
	if in == nil {
		return nil
	}
	out := new(DatabaseBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileReplicaSpec) DeepCopyInto(out *FileReplicaSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileReplicaSpec.
func (in *FileReplicaSpec) DeepCopy() *FileReplicaSpec {
	if in == nil {
		return nil
	}
	out := new(FileReplicaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCSReplicaSpec) DeepCopyInto(out *GCSReplicaSpec) {
	*out = *in
	if in.ServiceAccountJSON != nil {
		in, out := &in.ServiceAccountJSON, &out.ServiceAccountJSON
		*out = new(SecretReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCSReplicaSpec.
func (in *GCSReplicaSpec) DeepCopy() *GCSReplicaSpec {
	if in == nil {
		return nil
	}
	out := new(GCSReplicaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InjectionSpec) DeepCopyInto(out *InjectionSpec) {
	*out = *in
	if in.ExtraVolumeMounts != nil {
		in, out := &in.ExtraVolumeMounts, &out.ExtraVolumeMounts
		*out = make([]v1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerSecurityContext != nil {
		in, out := &in.ContainerSecurityContext, &out.ContainerSecurityContext
		*out = new(v1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	out.Permissions = in.Permissions
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InjectionSpec.
func (in *InjectionSpec) DeepCopy() *InjectionSpec {
	if in == nil {
		return nil
	}
	out := new(InjectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Litestream) DeepCopyInto(out *Litestream) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Litestream.
func (in *Litestream) DeepCopy() *Litestream {
	if in == nil {
		return nil
	}
	out := new(Litestream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Litestream) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LitestreamList) DeepCopyInto(out *LitestreamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Litestream, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LitestreamList.
func (in *LitestreamList) DeepCopy() *LitestreamList {
	if in == nil {
		return nil
	}
	out := new(LitestreamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LitestreamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LitestreamReplica) DeepCopyInto(out *LitestreamReplica) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LitestreamReplica.
func (in *LitestreamReplica) DeepCopy() *LitestreamReplica {
	if in == nil {
		return nil
	}
	out := new(LitestreamReplica)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LitestreamReplica) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LitestreamReplicaList) DeepCopyInto(out *LitestreamReplicaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LitestreamReplica, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LitestreamReplicaList.
func (in *LitestreamReplicaList) DeepCopy() *LitestreamReplicaList {
	if in == nil {
		return nil
	}
	out := new(LitestreamReplicaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LitestreamReplicaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LitestreamReplicaSpec) DeepCopyInto(out *LitestreamReplicaSpec) {
	*out = *in
	in.Replica.DeepCopyInto(&out.Replica)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LitestreamReplicaSpec.
func (in *LitestreamReplicaSpec) DeepCopy() *LitestreamReplicaSpec {
	if in == nil {
		return nil
	}
	out := new(LitestreamReplicaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LitestreamSpec) DeepCopyInto(out *LitestreamSpec) {
	*out = *in
	out.Image = in.Image
	in.Injection.DeepCopyInto(&out.Injection)
	if in.Databases != nil {
		in, out := &in.Databases, &out.Databases
		*out = make([]DatabaseBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LitestreamSpec.
func (in *LitestreamSpec) DeepCopy() *LitestreamSpec {
	if in == nil {
		return nil
	}
	out := new(LitestreamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LitestreamStatus) DeepCopyInto(out *LitestreamStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LitestreamStatus.
func (in *LitestreamStatus) DeepCopy() *LitestreamStatus {
	if in == nil {
		return nil
	}
	out := new(LitestreamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NATSReplicaSpec) DeepCopyInto(out *NATSReplicaSpec) {
	*out = *in
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(SecretReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(SecretReference)
		(*in).DeepCopyInto(*out)
	}
	if in.JWT != nil {
		in, out := &in.JWT, &out.JWT
		*out = new(SecretReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Seed != nil {
		in, out := &in.Seed, &out.Seed
		*out = new(SecretReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Creds != nil {
		in, out := &in.Creds, &out.Creds
		*out = new(SecretReference)
		(*in).DeepCopyInto(*out)
	}
	if in.NKey != nil {
		in, out := &in.NKey, &out.NKey
		*out = new(SecretReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(SecretReference)
		(*in).DeepCopyInto(*out)
	}
	if in.RootCAs != nil {
		in, out := &in.RootCAs, &out.RootCAs
		*out = make([]SecretReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClientCert != nil {
		in, out := &in.ClientCert, &out.ClientCert
		*out = new(SecretReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientKey != nil {
		in, out := &in.ClientKey, &out.ClientKey
		*out = new(SecretReference)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxReconnects != nil {
		in, out := &in.MaxReconnects, &out.MaxReconnects
		*out = new(int)
		**out = **in
	}
	if in.ReconnectWait != nil {
		in, out := &in.ReconnectWait, &out.ReconnectWait
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NATSReplicaSpec.
func (in *NATSReplicaSpec) DeepCopy() *NATSReplicaSpec {
	if in == nil {
		return nil
	}
	out := new(NATSReplicaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OSSReplicaSpec) DeepCopyInto(out *OSSReplicaSpec) {
	*out = *in
	if in.AccessKeyID != nil {
		in, out := &in.AccessKeyID, &out.AccessKeyID
		*out = new(SecretReference)
		(*in).DeepCopyInto(*out)
	}
	if in.AccessKeySecret != nil {
		in, out := &in.AccessKeySecret, &out.AccessKeySecret
		*out = new(SecretReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OSSReplicaSpec.
func (in *OSSReplicaSpec) DeepCopy() *OSSReplicaSpec {
	if in == nil {
		return nil
	}
	out := new(OSSReplicaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PermissionsSpec) DeepCopyInto(out *PermissionsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PermissionsSpec.
func (in *PermissionsSpec) DeepCopy() *PermissionsSpec {
	if in == nil {
		return nil
	}
	out := new(PermissionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaSpec) DeepCopyInto(out *ReplicaSpec) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3ReplicaSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.GCS != nil {
		in, out := &in.GCS, &out.GCS
		*out = new(GCSReplicaSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(AzureReplicaSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.File != nil {
		in, out := &in.File, &out.File
		*out = new(FileReplicaSpec)
		**out = **in
	}
	if in.NATS != nil {
		in, out := &in.NATS, &out.NATS
		*out = new(NATSReplicaSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OSS != nil {
		in, out := &in.OSS, &out.OSS
		*out = new(OSSReplicaSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SFTP != nil {
		in, out := &in.SFTP, &out.SFTP
		*out = new(SFTPReplicaSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.WebDAV != nil {
		in, out := &in.WebDAV, &out.WebDAV
		*out = new(WebDAVReplicaSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaSpec.
func (in *ReplicaSpec) DeepCopy() *ReplicaSpec {
	if in == nil {
		return nil
	}
	out := new(ReplicaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicateSpec) DeepCopyInto(out *ReplicateSpec) {
	*out = *in
	out.ReplicaRef = in.ReplicaRef
	out.SyncInterval = in.SyncInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicateSpec.
func (in *ReplicateSpec) DeepCopy() *ReplicateSpec {
	if in == nil {
		return nil
	}
	out := new(ReplicateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreSpec) DeepCopyInto(out *RestoreSpec) {
	*out = *in
	out.ReplicaRef = in.ReplicaRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreSpec.
func (in *RestoreSpec) DeepCopy() *RestoreSpec {
	if in == nil {
		return nil
	}
	out := new(RestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Credentials) DeepCopyInto(out *S3Credentials) {
	*out = *in
	if in.AccessKeyID != nil {
		in, out := &in.AccessKeyID, &out.AccessKeyID
		*out = new(SecretReference)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretAccessKey != nil {
		in, out := &in.SecretAccessKey, &out.SecretAccessKey
		*out = new(SecretReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Credentials.
func (in *S3Credentials) DeepCopy() *S3Credentials {
	if in == nil {
		return nil
	}
	out := new(S3Credentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3ReplicaSpec) DeepCopyInto(out *S3ReplicaSpec) {
	*out = *in
	if in.ForcePathStyle != nil {
		in, out := &in.ForcePathStyle, &out.ForcePathStyle
		*out = new(bool)
		**out = **in
	}
	if in.SkipVerify != nil {
		in, out := &in.SkipVerify, &out.SkipVerify
		*out = new(bool)
		**out = **in
	}
	in.Credentials.DeepCopyInto(&out.Credentials)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3ReplicaSpec.
func (in *S3ReplicaSpec) DeepCopy() *S3ReplicaSpec {
	if in == nil {
		return nil
	}
	out := new(S3ReplicaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SFTPReplicaSpec) DeepCopyInto(out *SFTPReplicaSpec) {
	*out = *in
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(SecretReference)
		(*in).DeepCopyInto(*out)
	}
	if in.PrivateKey != nil {
		in, out := &in.PrivateKey, &out.PrivateKey
		*out = new(SecretReference)
		(*in).DeepCopyInto(*out)
	}
	if in.ConcurrentWrites != nil {
		in, out := &in.ConcurrentWrites, &out.ConcurrentWrites
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SFTPReplicaSpec.
func (in *SFTPReplicaSpec) DeepCopy() *SFTPReplicaSpec {
	if in == nil {
		return nil
	}
	out := new(SFTPReplicaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
	in.SecretKeyRef.DeepCopyInto(&out.SecretKeyRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebDAVReplicaSpec) DeepCopyInto(out *WebDAVReplicaSpec) {
	*out = *in
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(SecretReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(SecretReference)
		(*in).DeepCopyInto(*out)
	}
	if in.SkipVerify != nil {
		in, out := &in.SkipVerify, &out.SkipVerify
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebDAVReplicaSpec.
func (in *WebDAVReplicaSpec) DeepCopy() *WebDAVReplicaSpec {
	if in == nil {
		return nil
	}
	out := new(WebDAVReplicaSpec)
	in.DeepCopyInto(out)
	return out
}
