version: 2

builds:
  - id: ff
    main: ./cmd/ff
    binary: ff
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - id: sarif-to-codequality
    main: ./cmd/sarif-to-codequality
    binary: sarif-to-codequality
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - id: nip05
    main: ./cmd/nip05
    binary: nip05
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - id: wsl-keyring
    main: ./cmd/wsl-keyring
    binary: wsl-keyring
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - binary
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .Binary }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
