// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storesqlc

type DeletionTombstone struct {
	OwnerPubkey     string
	TargetEventID   string
	DeletionEventID string
	CreatedAt       int64
}

type Event struct {
	ID        string
	Pubkey    string
	CreatedAt int64
	Kind      int64
	EventJson string
}

type Nip98SeenEvent struct {
	EventID string
	SeenAt  int64
}

type PublisherAllowlist struct {
	Pubkey    string
	Reason    string
	CreatedAt int64
}
