// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package storesqlc

import (
	"context"
	"database/sql"
)

const allEvents = `-- name: AllEvents :many
SELECT event_json
FROM events
WHERE
    (NOT ?1 OR id IN (SELECT value FROM json_each(?2)))
    AND (NOT ?3 OR pubkey IN (SELECT value FROM json_each(?4)))
    AND (NOT ?5 OR kind IN (SELECT value FROM json_each(?6)))
    AND (NOT ?7 OR created_at >= ?8)
    AND (NOT ?9 OR created_at <= ?10)
    AND (NOT ?11 OR NOT EXISTS (
        SELECT 1
        FROM json_each(?12) AS requested_tag
        WHERE NOT EXISTS (
            SELECT 1
            FROM json_each(json_extract(events.event_json, '$.tags')) AS event_tag
            WHERE json_extract(event_tag.value, '$[0]') = requested_tag.key
              AND json_extract(event_tag.value, '$[1]') IN (
                  SELECT value FROM json_each(requested_tag.value)
              )
        )
    ))
ORDER BY created_at DESC, id ASC
LIMIT CASE WHEN ?13 > 0 THEN ?13 ELSE -1 END
`

type AllEventsParams struct {
	HasIds      interface{}
	IdsJson     interface{}
	HasAuthors  interface{}
	AuthorsJson interface{}
	HasKinds    interface{}
	KindsJson   interface{}
	HasSince    interface{}
	Since       int64
	HasUntil    interface{}
	Until       int64
	HasTags     interface{}
	TagsJson    interface{}
	ResultLimit interface{}
}

func (q *Queries) AllEvents(ctx context.Context, arg AllEventsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, allEvents,
		arg.HasIds,
		arg.IdsJson,
		arg.HasAuthors,
		arg.AuthorsJson,
		arg.HasKinds,
		arg.KindsJson,
		arg.HasSince,
		arg.Since,
		arg.HasUntil,
		arg.Until,
		arg.HasTags,
		arg.TagsJson,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var event_json string
		if err := rows.Scan(&event_json); err != nil {
			return nil, err
		}
		items = append(items, event_json)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const allowPublisher = `-- name: AllowPublisher :exec
INSERT INTO publisher_allowlist (pubkey, reason, created_at)
VALUES (?, ?, ?)
ON CONFLICT(pubkey) DO UPDATE
SET reason = excluded.reason, created_at = excluded.created_at
`

type AllowPublisherParams struct {
	Pubkey    string
	Reason    string
	CreatedAt int64
}

func (q *Queries) AllowPublisher(ctx context.Context, arg AllowPublisherParams) error {
	_, err := q.db.ExecContext(ctx, allowPublisher, arg.Pubkey, arg.Reason, arg.CreatedAt)
	return err
}

const consumeNIP98Event = `-- name: ConsumeNIP98Event :execresult
INSERT OR IGNORE INTO nip98_seen_events(event_id, seen_at) VALUES(?, ?)
`

type ConsumeNIP98EventParams struct {
	EventID string
	SeenAt  int64
}

func (q *Queries) ConsumeNIP98Event(ctx context.Context, arg ConsumeNIP98EventParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, consumeNIP98Event, arg.EventID, arg.SeenAt)
}

const deleteEventByID = `-- name: DeleteEventByID :exec
DELETE FROM events WHERE id = ?
`

func (q *Queries) DeleteEventByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEventByID, id)
	return err
}

const deleteExpiredNIP98Events = `-- name: DeleteExpiredNIP98Events :exec
DELETE FROM nip98_seen_events WHERE seen_at < ?
`

func (q *Queries) DeleteExpiredNIP98Events(ctx context.Context, seenAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredNIP98Events, seenAt)
	return err
}

const deleteOwnedEvent = `-- name: DeleteOwnedEvent :exec
DELETE FROM events WHERE id = ? AND pubkey = ?
`

type DeleteOwnedEventParams struct {
	ID     string
	Pubkey string
}

func (q *Queries) DeleteOwnedEvent(ctx context.Context, arg DeleteOwnedEventParams) error {
	_, err := q.db.ExecContext(ctx, deleteOwnedEvent, arg.ID, arg.Pubkey)
	return err
}

const eventByID = `-- name: EventByID :one
SELECT event_json FROM events WHERE id = ?
`

func (q *Queries) EventByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, eventByID, id)
	var event_json string
	err := row.Scan(&event_json)
	return event_json, err
}

const eventTombstoned = `-- name: EventTombstoned :one
SELECT EXISTS(
    SELECT 1
    FROM deletion_tombstones
    WHERE owner_pubkey = ? AND target_event_id = ?
)
`

type EventTombstonedParams struct {
	OwnerPubkey   string
	TargetEventID string
}

func (q *Queries) EventTombstoned(ctx context.Context, arg EventTombstonedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, eventTombstoned, arg.OwnerPubkey, arg.TargetEventID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const eventsByPubKeyAndKind = `-- name: EventsByPubKeyAndKind :many
SELECT id, event_json
FROM events
WHERE pubkey = ? AND kind = ?
`

type EventsByPubKeyAndKindParams struct {
	Pubkey string
	Kind   int64
}

type EventsByPubKeyAndKindRow struct {
	ID        string
	EventJson string
}

func (q *Queries) EventsByPubKeyAndKind(ctx context.Context, arg EventsByPubKeyAndKindParams) ([]EventsByPubKeyAndKindRow, error) {
	rows, err := q.db.QueryContext(ctx, eventsByPubKeyAndKind, arg.Pubkey, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventsByPubKeyAndKindRow
	for rows.Next() {
		var i EventsByPubKeyAndKindRow
		if err := rows.Scan(&i.ID, &i.EventJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDeletionTombstone = `-- name: InsertDeletionTombstone :exec
INSERT OR IGNORE INTO deletion_tombstones
    (owner_pubkey, target_event_id, deletion_event_id, created_at)
VALUES (?, ?, ?, ?)
`

type InsertDeletionTombstoneParams struct {
	OwnerPubkey     string
	TargetEventID   string
	DeletionEventID string
	CreatedAt       int64
}

func (q *Queries) InsertDeletionTombstone(ctx context.Context, arg InsertDeletionTombstoneParams) error {
	_, err := q.db.ExecContext(ctx, insertDeletionTombstone,
		arg.OwnerPubkey,
		arg.TargetEventID,
		arg.DeletionEventID,
		arg.CreatedAt,
	)
	return err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT OR IGNORE INTO events (id, pubkey, created_at, kind, event_json)
VALUES (?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	ID        string
	Pubkey    string
	CreatedAt int64
	Kind      int64
	EventJson string
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.ID,
		arg.Pubkey,
		arg.CreatedAt,
		arg.Kind,
		arg.EventJson,
	)
	return err
}

const listPublishers = `-- name: ListPublishers :many
SELECT pubkey, reason, created_at
FROM publisher_allowlist
ORDER BY pubkey
`

func (q *Queries) ListPublishers(ctx context.Context) ([]PublisherAllowlist, error) {
	rows, err := q.db.QueryContext(ctx, listPublishers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublisherAllowlist
	for rows.Next() {
		var i PublisherAllowlist
		if err := rows.Scan(&i.Pubkey, &i.Reason, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publisherAllowed = `-- name: PublisherAllowed :one
SELECT EXISTS(SELECT 1 FROM publisher_allowlist WHERE pubkey = ?)
`

func (q *Queries) PublisherAllowed(ctx context.Context, pubkey string) (bool, error) {
	row := q.db.QueryRowContext(ctx, publisherAllowed, pubkey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const unallowPublisher = `-- name: UnallowPublisher :exec
DELETE FROM publisher_allowlist WHERE pubkey = ?
`

func (q *Queries) UnallowPublisher(ctx context.Context, pubkey string) error {
	_, err := q.db.ExecContext(ctx, unallowPublisher, pubkey)
	return err
}
