// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storesqlc

type BridgeEvent struct {
	SourceUri    string
	NostrEventID string
	SourceKind   string
	AuthorPubkey string
	UpdatedAt    int64
}

type OauthSession struct {
	State            string
	EncryptedPayload []byte
	ExpiresAt        int64
}

type OauthToken struct {
	AccountDid       string
	EncryptedPayload []byte
	UpdatedAt        int64
}

type Outbox struct {
	ID           int64
	AggregateKey string
	Sequence     int64
	Operation    string
	Pubkey       string
	Payload      string
	Attempts     int64
	AvailableAt  int64
	LastError    string
	ClaimToken   string
	ClaimedUntil int64
}

type OutboxSequence struct {
	AggregateKey string
	LastSequence int64
}

type PublisherPurge struct {
	Pubkey          string
	DeletionEventID string
	CreatedAt       int64
}

type PublisherRegistration struct {
	Pubkey       string
	RegisteredAt int64
}

type SourceOperation struct {
	SourceUri string
	Identity  string
}

type SyncCursor struct {
	Name  string
	Value int64
}

type SyncTarget struct {
	Did string
}
