// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storesqlc

type BridgeEvent struct {
	Provider      string
	SourceAccount string
	SourceUri     string
	NostrEventID  string
	SourceKind    string
	AuthorPubkey  string
	UpdatedAt     int64
}

type OauthSession struct {
	Provider         string
	SourceAccount    string
	State            string
	EncryptedPayload []byte
	ExpiresAt        int64
}

type OauthToken struct {
	Provider         string
	SourceAccount    string
	AccountDid       string
	EncryptedPayload []byte
	UpdatedAt        int64
}

type Outbox struct {
	ID           int64
	AggregateKey string
	Sequence     int64
	Operation    string
	Pubkey       string
	Payload      string
	Attempts     int64
	AvailableAt  int64
	LastError    string
	ClaimToken   string
	ClaimedUntil int64
}

type OutboxSequence struct {
	AggregateKey string
	LastSequence int64
}

type PublisherPurge struct {
	Pubkey          string
	DeletionEventID string
	CreatedAt       int64
}

type PublisherRegistration struct {
	Pubkey       string
	RegisteredAt int64
}

type SourceOperation struct {
	Provider      string
	SourceAccount string
	SourceUri     string
	Identity      string
}

type SyncCursor struct {
	Provider      string
	SourceAccount string
	Name          string
	Value         string
}

type SyncTarget struct {
	Provider      string
	SourceAccount string
	Target        string
}
