// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package storesqlc

import (
	"context"
	"database/sql"
)

const advanceOutboxSequence = `-- name: AdvanceOutboxSequence :exec
INSERT INTO outbox_sequences(aggregate_key, last_sequence) VALUES(?, 1)
ON CONFLICT(aggregate_key) DO UPDATE SET last_sequence=last_sequence+1
`

func (q *Queries) AdvanceOutboxSequence(ctx context.Context, aggregateKey string) error {
	_, err := q.db.ExecContext(ctx, advanceOutboxSequence, aggregateKey)
	return err
}

const claimOutbox = `-- name: ClaimOutbox :many
UPDATE outbox SET claim_token=?1, claimed_until=?2
WHERE id IN (
 SELECT o.id FROM outbox o WHERE (o.claim_token = '' OR o.claimed_until <= ?3) AND o.available_at <= ?4
 AND NOT EXISTS (SELECT 1 FROM outbox prior WHERE prior.aggregate_key=o.aggregate_key AND prior.` + "`" + `sequence` + "`" + `<o.` + "`" + `sequence` + "`" + `)
 ORDER BY o.available_at, o.id LIMIT ?5
) AND (claim_token = '' OR claimed_until <= ?3)
RETURNING id, aggregate_key, ` + "`" + `sequence` + "`" + `, operation, pubkey, payload, attempts, available_at, last_error
`

type ClaimOutboxParams struct {
	ClaimToken   string
	ClaimedUntil int64
	NowNanos     int64
	NowSeconds   int64
	ResultLimit  int64
}

type ClaimOutboxRow struct {
	ID           int64
	AggregateKey string
	Sequence     int64
	Operation    string
	Pubkey       string
	Payload      string
	Attempts     int64
	AvailableAt  int64
	LastError    string
}

func (q *Queries) ClaimOutbox(ctx context.Context, arg ClaimOutboxParams) ([]ClaimOutboxRow, error) {
	rows, err := q.db.QueryContext(ctx, claimOutbox,
		arg.ClaimToken,
		arg.ClaimedUntil,
		arg.NowNanos,
		arg.NowSeconds,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimOutboxRow
	for rows.Next() {
		var i ClaimOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.AggregateKey,
			&i.Sequence,
			&i.Operation,
			&i.Pubkey,
			&i.Payload,
			&i.Attempts,
			&i.AvailableAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimedPublishEvent = `-- name: ClaimedPublishEvent :one
SELECT aggregate_key,` + "`" + `sequence` + "`" + `,payload FROM outbox WHERE id=? AND claim_token=? AND claim_token<>'' AND claimed_until>? AND operation='publish-event'
`

type ClaimedPublishEventParams struct {
	ID           int64
	ClaimToken   string
	ClaimedUntil int64
}

type ClaimedPublishEventRow struct {
	AggregateKey string
	Sequence     int64
	Payload      string
}

func (q *Queries) ClaimedPublishEvent(ctx context.Context, arg ClaimedPublishEventParams) (ClaimedPublishEventRow, error) {
	row := q.db.QueryRowContext(ctx, claimedPublishEvent, arg.ID, arg.ClaimToken, arg.ClaimedUntil)
	var i ClaimedPublishEventRow
	err := row.Scan(&i.AggregateKey, &i.Sequence, &i.Payload)
	return i, err
}

const clearPublisherRegistration = `-- name: ClearPublisherRegistration :exec
DELETE FROM publisher_registrations WHERE pubkey=?
`

func (q *Queries) ClearPublisherRegistration(ctx context.Context, pubkey string) error {
	_, err := q.db.ExecContext(ctx, clearPublisherRegistration, pubkey)
	return err
}

const completeOutbox = `-- name: CompleteOutbox :execresult
DELETE FROM outbox WHERE id=? AND claim_token=? AND claim_token<>'' AND claimed_until>?
`

type CompleteOutboxParams struct {
	ID           int64
	ClaimToken   string
	ClaimedUntil int64
}

func (q *Queries) CompleteOutbox(ctx context.Context, arg CompleteOutboxParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, completeOutbox, arg.ID, arg.ClaimToken, arg.ClaimedUntil)
}

const cursor = `-- name: Cursor :one
SELECT ` + "`" + `value` + "`" + ` AS cursor_value FROM sync_cursors WHERE name=?
`

func (q *Queries) Cursor(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, cursor, name)
	var cursor_value int64
	err := row.Scan(&cursor_value)
	return cursor_value, err
}

const deleteEventMapping = `-- name: DeleteEventMapping :exec
DELETE FROM bridge_events WHERE source_uri=?
`

func (q *Queries) DeleteEventMapping(ctx context.Context, sourceUri string) error {
	_, err := q.db.ExecContext(ctx, deleteEventMapping, sourceUri)
	return err
}

const deleteOAuthSession = `-- name: DeleteOAuthSession :exec
DELETE FROM oauth_sessions WHERE state=?
`

func (q *Queries) DeleteOAuthSession(ctx context.Context, state string) error {
	_, err := q.db.ExecContext(ctx, deleteOAuthSession, state)
	return err
}

const deletePublisherMappings = `-- name: DeletePublisherMappings :exec
DELETE FROM bridge_events WHERE author_pubkey=?
`

func (q *Queries) DeletePublisherMappings(ctx context.Context, authorPubkey string) error {
	_, err := q.db.ExecContext(ctx, deletePublisherMappings, authorPubkey)
	return err
}

const deletePublisherSourceOperations = `-- name: DeletePublisherSourceOperations :exec
DELETE FROM source_operations WHERE source_uri IN (SELECT source_uri FROM bridge_events WHERE author_pubkey=?)
`

func (q *Queries) DeletePublisherSourceOperations(ctx context.Context, authorPubkey string) error {
	_, err := q.db.ExecContext(ctx, deletePublisherSourceOperations, authorPubkey)
	return err
}

const deleteSourceOperation = `-- name: DeleteSourceOperation :exec
DELETE FROM source_operations WHERE source_uri=?
`

func (q *Queries) DeleteSourceOperation(ctx context.Context, sourceUri string) error {
	_, err := q.db.ExecContext(ctx, deleteSourceOperation, sourceUri)
	return err
}

const enqueueOutbox = `-- name: EnqueueOutbox :exec
INSERT INTO outbox (aggregate_key, ` + "`" + `sequence` + "`" + `, operation, pubkey, payload, available_at)
SELECT ?1, last_sequence, ?2, ?3, ?4, ?5
FROM outbox_sequences WHERE outbox_sequences.aggregate_key=?6
`

type EnqueueOutboxParams struct {
	AggregateKey         string
	Operation            string
	Pubkey               string
	Payload              string
	AvailableAt          int64
	SequenceAggregateKey string
}

func (q *Queries) EnqueueOutbox(ctx context.Context, arg EnqueueOutboxParams) error {
	_, err := q.db.ExecContext(ctx, enqueueOutbox,
		arg.AggregateKey,
		arg.Operation,
		arg.Pubkey,
		arg.Payload,
		arg.AvailableAt,
		arg.SequenceAggregateKey,
	)
	return err
}

const eventAuthorBySourceURI = `-- name: EventAuthorBySourceURI :one
SELECT author_pubkey FROM bridge_events WHERE source_uri=?
`

func (q *Queries) EventAuthorBySourceURI(ctx context.Context, sourceUri string) (string, error) {
	row := q.db.QueryRowContext(ctx, eventAuthorBySourceURI, sourceUri)
	var author_pubkey string
	err := row.Scan(&author_pubkey)
	return author_pubkey, err
}

const eventIDBySourceURI = `-- name: EventIDBySourceURI :one
SELECT nostr_event_id FROM bridge_events WHERE source_uri=?
`

func (q *Queries) EventIDBySourceURI(ctx context.Context, sourceUri string) (string, error) {
	row := q.db.QueryRowContext(ctx, eventIDBySourceURI, sourceUri)
	var nostr_event_id string
	err := row.Scan(&nostr_event_id)
	return nostr_event_id, err
}

const eventIDsByAuthor = `-- name: EventIDsByAuthor :many
SELECT DISTINCT nostr_event_id FROM bridge_events WHERE author_pubkey=? ORDER BY nostr_event_id
`

func (q *Queries) EventIDsByAuthor(ctx context.Context, authorPubkey string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, eventIDsByAuthor, authorPubkey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var nostr_event_id string
		if err := rows.Scan(&nostr_event_id); err != nil {
			return nil, err
		}
		items = append(items, nostr_event_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventMappingBySourceURI = `-- name: EventMappingBySourceURI :one
SELECT source_uri, nostr_event_id, source_kind, author_pubkey, updated_at FROM bridge_events WHERE source_uri=?
`

func (q *Queries) EventMappingBySourceURI(ctx context.Context, sourceUri string) (BridgeEvent, error) {
	row := q.db.QueryRowContext(ctx, eventMappingBySourceURI, sourceUri)
	var i BridgeEvent
	err := row.Scan(
		&i.SourceUri,
		&i.NostrEventID,
		&i.SourceKind,
		&i.AuthorPubkey,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementOutboxLastSequence = `-- name: IncrementOutboxLastSequence :exec
UPDATE outbox_sequences SET last_sequence=last_sequence+1 WHERE aggregate_key=?
`

func (q *Queries) IncrementOutboxLastSequence(ctx context.Context, aggregateKey string) error {
	_, err := q.db.ExecContext(ctx, incrementOutboxLastSequence, aggregateKey)
	return err
}

const insertPublisherPurge = `-- name: InsertPublisherPurge :exec
INSERT INTO publisher_purges(pubkey,deletion_event_id,created_at) VALUES(?,?,?)
`

type InsertPublisherPurgeParams struct {
	Pubkey          string
	DeletionEventID string
	CreatedAt       int64
}

func (q *Queries) InsertPublisherPurge(ctx context.Context, arg InsertPublisherPurgeParams) error {
	_, err := q.db.ExecContext(ctx, insertPublisherPurge, arg.Pubkey, arg.DeletionEventID, arg.CreatedAt)
	return err
}

const insertRecoveredPublish = `-- name: InsertRecoveredPublish :exec
INSERT INTO outbox(aggregate_key,` + "`" + `sequence` + "`" + `,operation,pubkey,payload,available_at) VALUES(?,?,'publish-event',?,?,?)
`

type InsertRecoveredPublishParams struct {
	AggregateKey string
	Sequence     int64
	Pubkey       string
	Payload      string
	AvailableAt  int64
}

func (q *Queries) InsertRecoveredPublish(ctx context.Context, arg InsertRecoveredPublishParams) error {
	_, err := q.db.ExecContext(ctx, insertRecoveredPublish,
		arg.AggregateKey,
		arg.Sequence,
		arg.Pubkey,
		arg.Payload,
		arg.AvailableAt,
	)
	return err
}

const insertSyncTarget = `-- name: InsertSyncTarget :exec
INSERT OR IGNORE INTO sync_targets(did) VALUES(?)
`

func (q *Queries) InsertSyncTarget(ctx context.Context, did string) error {
	_, err := q.db.ExecContext(ctx, insertSyncTarget, did)
	return err
}

const negateLaterOutboxSequences = `-- name: NegateLaterOutboxSequences :exec
UPDATE outbox SET ` + "`" + `sequence` + "`" + `=-` + "`" + `sequence` + "`" + ` WHERE aggregate_key=? AND ` + "`" + `sequence` + "`" + `>?
`

type NegateLaterOutboxSequencesParams struct {
	AggregateKey string
	Sequence     int64
}

func (q *Queries) NegateLaterOutboxSequences(ctx context.Context, arg NegateLaterOutboxSequencesParams) error {
	_, err := q.db.ExecContext(ctx, negateLaterOutboxSequences, arg.AggregateKey, arg.Sequence)
	return err
}

const oAuthSessionByState = `-- name: OAuthSessionByState :one
SELECT state,encrypted_payload,expires_at FROM oauth_sessions WHERE state=?
`

func (q *Queries) OAuthSessionByState(ctx context.Context, state string) (OauthSession, error) {
	row := q.db.QueryRowContext(ctx, oAuthSessionByState, state)
	var i OauthSession
	err := row.Scan(&i.State, &i.EncryptedPayload, &i.ExpiresAt)
	return i, err
}

const oAuthTokenByAccountDID = `-- name: OAuthTokenByAccountDID :one
SELECT account_did,encrypted_payload,updated_at FROM oauth_tokens WHERE account_did=?
`

func (q *Queries) OAuthTokenByAccountDID(ctx context.Context, accountDid string) (OauthToken, error) {
	row := q.db.QueryRowContext(ctx, oAuthTokenByAccountDID, accountDid)
	var i OauthToken
	err := row.Scan(&i.AccountDid, &i.EncryptedPayload, &i.UpdatedAt)
	return i, err
}

const outboxCount = `-- name: OutboxCount :one
SELECT COUNT(*) FROM outbox
`

func (q *Queries) OutboxCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, outboxCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const publisherPurgeEvent = `-- name: PublisherPurgeEvent :one
SELECT deletion_event_id FROM publisher_purges WHERE pubkey=?
`

func (q *Queries) PublisherPurgeEvent(ctx context.Context, pubkey string) (string, error) {
	row := q.db.QueryRowContext(ctx, publisherPurgeEvent, pubkey)
	var deletion_event_id string
	err := row.Scan(&deletion_event_id)
	return deletion_event_id, err
}

const publisherPurged = `-- name: PublisherPurged :one
SELECT EXISTS(SELECT 1 FROM publisher_purges WHERE publisher_purges.pubkey=?1)
`

func (q *Queries) PublisherPurged(ctx context.Context, pubkey string) (bool, error) {
	row := q.db.QueryRowContext(ctx, publisherPurged, pubkey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const publisherRegistered = `-- name: PublisherRegistered :one
SELECT EXISTS(SELECT 1 FROM publisher_registrations WHERE pubkey=?)
`

func (q *Queries) PublisherRegistered(ctx context.Context, pubkey string) (bool, error) {
	row := q.db.QueryRowContext(ctx, publisherRegistered, pubkey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const publisherRegisteredOrPending = `-- name: PublisherRegisteredOrPending :one
SELECT EXISTS(SELECT 1 FROM publisher_registrations WHERE publisher_registrations.pubkey=?1 UNION ALL SELECT 1 FROM outbox WHERE aggregate_key=?2 AND operation='allow-publisher')
`

type PublisherRegisteredOrPendingParams struct {
	Pubkey       string
	AggregateKey string
}

func (q *Queries) PublisherRegisteredOrPending(ctx context.Context, arg PublisherRegisteredOrPendingParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, publisherRegisteredOrPending, arg.Pubkey, arg.AggregateKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const publisherUnallowPending = `-- name: PublisherUnallowPending :one
SELECT EXISTS(SELECT 1 FROM outbox WHERE aggregate_key=? AND operation='unallow-publisher')
`

func (q *Queries) PublisherUnallowPending(ctx context.Context, aggregateKey string) (bool, error) {
	row := q.db.QueryRowContext(ctx, publisherUnallowPending, aggregateKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const replaceSyncTargetsDelete = `-- name: ReplaceSyncTargetsDelete :exec
DELETE FROM sync_targets
`

func (q *Queries) ReplaceSyncTargetsDelete(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, replaceSyncTargetsDelete)
	return err
}

const resetRejectedPublishAsRegistration = `-- name: ResetRejectedPublishAsRegistration :exec
UPDATE outbox SET operation='allow-publisher',payload='',attempts=0,last_error='',claim_token='',claimed_until=0,available_at=? WHERE id=?
`

type ResetRejectedPublishAsRegistrationParams struct {
	AvailableAt int64
	ID          int64
}

func (q *Queries) ResetRejectedPublishAsRegistration(ctx context.Context, arg ResetRejectedPublishAsRegistrationParams) error {
	_, err := q.db.ExecContext(ctx, resetRejectedPublishAsRegistration, arg.AvailableAt, arg.ID)
	return err
}

const retryOutbox = `-- name: RetryOutbox :execresult
UPDATE outbox SET attempts=attempts+1, available_at=?, last_error=?, claim_token='', claimed_until=0 WHERE id=? AND claim_token=? AND claim_token<>'' AND claimed_until>?
`

type RetryOutboxParams struct {
	AvailableAt  int64
	LastError    string
	ID           int64
	ClaimToken   string
	ClaimedUntil int64
}

func (q *Queries) RetryOutbox(ctx context.Context, arg RetryOutboxParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, retryOutbox,
		arg.AvailableAt,
		arg.LastError,
		arg.ID,
		arg.ClaimToken,
		arg.ClaimedUntil,
	)
}

const saveCursor = `-- name: SaveCursor :exec
INSERT INTO sync_cursors(name,` + "`" + `value` + "`" + `) VALUES(?,?) ON CONFLICT(name) DO UPDATE SET ` + "`" + `value` + "`" + `=excluded.` + "`" + `value` + "`" + `
`

type SaveCursorParams struct {
	Name  string
	Value int64
}

func (q *Queries) SaveCursor(ctx context.Context, arg SaveCursorParams) error {
	_, err := q.db.ExecContext(ctx, saveCursor, arg.Name, arg.Value)
	return err
}

const saveOAuthSession = `-- name: SaveOAuthSession :exec
INSERT INTO oauth_sessions(state,encrypted_payload,expires_at) VALUES(?,?,?) ON CONFLICT(state) DO UPDATE SET encrypted_payload=excluded.encrypted_payload,expires_at=excluded.expires_at
`

type SaveOAuthSessionParams struct {
	State            string
	EncryptedPayload []byte
	ExpiresAt        int64
}

func (q *Queries) SaveOAuthSession(ctx context.Context, arg SaveOAuthSessionParams) error {
	_, err := q.db.ExecContext(ctx, saveOAuthSession, arg.State, arg.EncryptedPayload, arg.ExpiresAt)
	return err
}

const saveOAuthToken = `-- name: SaveOAuthToken :exec
INSERT INTO oauth_tokens(account_did,encrypted_payload,updated_at) VALUES(?,?,?) ON CONFLICT(account_did) DO UPDATE SET encrypted_payload=excluded.encrypted_payload,updated_at=excluded.updated_at
`

type SaveOAuthTokenParams struct {
	AccountDid       string
	EncryptedPayload []byte
	UpdatedAt        int64
}

func (q *Queries) SaveOAuthToken(ctx context.Context, arg SaveOAuthTokenParams) error {
	_, err := q.db.ExecContext(ctx, saveOAuthToken, arg.AccountDid, arg.EncryptedPayload, arg.UpdatedAt)
	return err
}

const saveSourceOperation = `-- name: SaveSourceOperation :exec
INSERT INTO source_operations(source_uri,` + "`" + `identity` + "`" + `) VALUES(?,?) ON CONFLICT(source_uri) DO UPDATE SET ` + "`" + `identity` + "`" + `=excluded.` + "`" + `identity` + "`" + `
`

type SaveSourceOperationParams struct {
	SourceUri string
	Identity  string
}

func (q *Queries) SaveSourceOperation(ctx context.Context, arg SaveSourceOperationParams) error {
	_, err := q.db.ExecContext(ctx, saveSourceOperation, arg.SourceUri, arg.Identity)
	return err
}

const setPublisherRegistered = `-- name: SetPublisherRegistered :exec
INSERT INTO publisher_registrations(pubkey, registered_at) VALUES(?, ?)
ON CONFLICT(pubkey) DO UPDATE SET registered_at=excluded.registered_at
`

type SetPublisherRegisteredParams struct {
	Pubkey       string
	RegisteredAt int64
}

func (q *Queries) SetPublisherRegistered(ctx context.Context, arg SetPublisherRegisteredParams) error {
	_, err := q.db.ExecContext(ctx, setPublisherRegistered, arg.Pubkey, arg.RegisteredAt)
	return err
}

const shiftNegatedOutboxSequences = `-- name: ShiftNegatedOutboxSequences :exec
UPDATE outbox SET ` + "`" + `sequence` + "`" + `=(-` + "`" + `sequence` + "`" + `)+1 WHERE aggregate_key=? AND ` + "`" + `sequence` + "`" + `<0
`

func (q *Queries) ShiftNegatedOutboxSequences(ctx context.Context, aggregateKey string) error {
	_, err := q.db.ExecContext(ctx, shiftNegatedOutboxSequences, aggregateKey)
	return err
}

const sourceOperationBySourceURI = `-- name: SourceOperationBySourceURI :one
SELECT ` + "`" + `identity` + "`" + ` AS operation_identity FROM source_operations WHERE source_uri=?
`

func (q *Queries) SourceOperationBySourceURI(ctx context.Context, sourceUri string) (string, error) {
	row := q.db.QueryRowContext(ctx, sourceOperationBySourceURI, sourceUri)
	var operation_identity string
	err := row.Scan(&operation_identity)
	return operation_identity, err
}

const syncTargets = `-- name: SyncTargets :many
SELECT did FROM sync_targets ORDER BY did
`

func (q *Queries) SyncTargets(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, syncTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var did string
		if err := rows.Scan(&did); err != nil {
			return nil, err
		}
		items = append(items, did)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEventMapping = `-- name: UpsertEventMapping :exec
INSERT INTO bridge_events(source_uri,nostr_event_id,source_kind,author_pubkey,updated_at) VALUES(?,?,?,?,?)
ON CONFLICT(source_uri) DO UPDATE SET nostr_event_id=excluded.nostr_event_id,source_kind=excluded.source_kind,author_pubkey=excluded.author_pubkey,updated_at=excluded.updated_at
`

type UpsertEventMappingParams struct {
	SourceUri    string
	NostrEventID string
	SourceKind   string
	AuthorPubkey string
	UpdatedAt    int64
}

func (q *Queries) UpsertEventMapping(ctx context.Context, arg UpsertEventMappingParams) error {
	_, err := q.db.ExecContext(ctx, upsertEventMapping,
		arg.SourceUri,
		arg.NostrEventID,
		arg.SourceKind,
		arg.AuthorPubkey,
		arg.UpdatedAt,
	)
	return err
}
