apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- bases/litestream.mytools.nakatanakatana.app_litestreamreplicas.yaml
- bases/litestream.mytools.nakatanakatana.app_litestreams.yaml
