---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1-pod
  failurePolicy: Fail
  name: mpod.litestream-controller.mytools.nakatanakatana.app
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
  timeoutSeconds: 10
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-litestream
  failurePolicy: Fail
  name: vlitestream.litestream-controller.mytools.nakatanakatana.app
  rules:
  - apiGroups:
    - litestream.mytools.nakatanakatana.app
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - litestreams
  sideEffects: None
  timeoutSeconds: 10
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-litestreamreplica
  failurePolicy: Fail
  name: vlitestreamreplica.litestream-controller.mytools.nakatanakatana.app
  rules:
  - apiGroups:
    - litestream.mytools.nakatanakatana.app
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - litestreamreplicas
  sideEffects: None
  timeoutSeconds: 10
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-litestream-workload
  failurePolicy: Fail
  name: vlitestreamworkload.litestream-controller.mytools.nakatanakatana.app
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - deployments
    - deployments/scale
    - statefulsets
    - statefulsets/scale
    - daemonsets
  sideEffects: None
  timeoutSeconds: 10
