apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nostr-relay-data
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
  # storageClassName: REPLACE_WITH_STORAGE_CLASS
